# PersistentVolumeClaim definition for MySQL, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authdb-pv-claim
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce    #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.
---
# Deployment definition for MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: rootroot # Change as per your requirements
          - name: MYSQL_DATABASE
            value: auth_db
        volumeMounts:
          - name: authdb-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: authdb-persistent-storage
          persistentVolumeClaim:
            claimName: authdb-pv-claim
---
# Service definition to expose MySQL
apiVersion: v1
kind: Service
metadata:
  name: authdb-svc
  labels: # This labels block might be redundant
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None # Headless service, for DNS resolution between pods
