apiVersion: v1
kind: Service
metadata:
  name: auth-api-service  # Replace with your desired service name
spec:
  selector:
    app: auth-api
  ports:
  - protocol: TCP
    port: 90
    targetPort: 8080
  type: NodePort  # Adjust type (e.g., LoadBalancer, NodePort) if needed
