apiVersion: v1
kind: Service
metadata:
  name: ui-service  # Replace with your desired service name
spec:
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # Adjust type (e.g., LoadBalancer, NodePort) if needed
